name: Publicar en PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar build
        run: pip install build
      - name: Construir distribuciones
        run: python -m build
      - name: Publicar en PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{{{ secrets.PYPI_TOKEN }}}}
